# Generated by Django 3.0.7 on 2020-06-08 15:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kerdes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kerdes', models.TextField(max_length=500, unique='True', verbose_name='kérdés')),
                ('valasz', tinymce.models.HTMLField(max_length=2000, verbose_name='válasz')),
                ('publikalt', models.BooleanField(default='True', verbose_name='publikált')),
            ],
            options={
                'verbose_name': 'kérdés',
                'verbose_name_plural': 'kérdések',
                'ordering': ['kerdes'],
            },
        ),
    ]
