# Generated by Django 4.0.3 on 2022-03-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_squashed_0002_auto_20200608_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerdes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
