# Generated by Django 3.0.7 on 2020-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerdes',
            name='kerdes',
            field=models.TextField(max_length=500, verbose_name='kérdés'),
        ),
    ]
