# Generated by Django 5.2.4 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_kerdes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerdes',
            name='publikalt',
            field=models.BooleanField(default=True, verbose_name='publikált'),
        ),
    ]
