# Generated by Django 3.0.6 on 2020-05-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temakor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=255, unique='True', verbose_name='cím')),
            ],
            options={
                'verbose_name': 'téma',
                'verbose_name_plural': 'témák',
                'ordering': ['cim'],
            },
        ),
    ]
