# Generated by Django 3.0.6 on 2020-06-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0002_auto_20200601_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallgato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elotag', models.CharField(blank=True, max_length=20, verbose_name='előtag')),
                ('vezeteknev', models.CharField(max_length=100, verbose_name='vezetéknév')),
                ('keresztnev', models.CharField(max_length=100, verbose_name='keresztnév')),
                ('neptun_kod', models.CharField(max_length=6, verbose_name='neptun kód')),
            ],
            options={
                'verbose_name': 'hallgató',
                'verbose_name_plural': 'hallgatók',
                'ordering': ['vezeteknev', 'keresztnev'],
                'unique_together': {('vezeteknev', 'keresztnev', 'neptun_kod')},
            },
        ),
    ]
