# Generated by Django 3.0.6 on 2020-06-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0004_statusz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagozat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=20, unique='True', verbose_name='név')),
            ],
            options={
                'verbose_name': 'tagozat',
                'verbose_name_plural': 'tagozatok',
                'ordering': ['nev'],
            },
        ),
    ]
