# Generated by Django 3.0.6 on 2020-06-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0005_tagozat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErdemJegy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=15, unique='True', verbose_name='név')),
                ('ertek', models.IntegerField(unique='True', verbose_name='érték')),
            ],
            options={
                'verbose_name': 'érdemjegy',
                'verbose_name_plural': 'érdemjegyek',
                'ordering': ['ertek'],
                'unique_together': {('nev', 'ertek')},
            },
        ),
        migrations.CreateModel(
            name='HallgatoKepzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kezdet', models.DateField(verbose_name='kezdet')),
                ('veg', models.DateField(blank=True, null=True, verbose_name='vég')),
                ('hallgato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szakdolgozat.Hallgato', verbose_name='hallgató')),
            ],
            options={
                'verbose_name': 'hallgató képzése',
                'verbose_name_plural': 'hallgatók képzései',
                'ordering': ['hallgato', 'kezdet'],
            },
        ),
        migrations.CreateModel(
            name='Kepzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kepzes_kod', models.CharField(max_length=10, unique='True', verbose_name='képzés kód')),
                ('kepzes_nev', models.CharField(max_length=50, verbose_name='képzés név')),
                ('hallgatok', models.ManyToManyField(through='szakdolgozat.HallgatoKepzes', to='szakdolgozat.Hallgato', verbose_name='hallgatók')),
                ('tagozat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szakdolgozat.Tagozat', verbose_name='tagozat')),
            ],
            options={
                'verbose_name': 'képzés',
                'verbose_name_plural': 'képzések',
                'ordering': ['kepzes_kod'],
                'unique_together': {('kepzes_kod', 'kepzes_nev', 'tagozat')},
            },
        ),
        migrations.CreateModel(
            name='HallgatoKepzesTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kezdet', models.DateField(verbose_name='kezdet')),
                ('veg', models.DateField(blank=True, null=True, verbose_name='vég')),
                ('szakdolgozat_targyat_felvett', models.BooleanField(default=False, verbose_name='szakdolgozat tárgyat felvett vagy kérvény alapján segíti témavezető')),
                ('kerveny', models.CharField(choices=[('kerveny_00', 'Még nem volt kérvény'), ('kerveny_01', 'Első kérvény'), ('kerveny_02', 'Második kérvény')], default='kerveny_00', help_text='Ezt a mezőt még nem használjuk, az eggyel fentebb lévő mezőbe kell az erre vonatkozó adatot beírni.', max_length=12, verbose_name='hányszor kérvényezte a témavezetői segítséget')),
                ('erdemjegy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='szakdolgozat.ErdemJegy', verbose_name='érdemjegy')),
                ('hallgato_kepzes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szakdolgozat.HallgatoKepzes', verbose_name='hallgató képzése')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szakdolgozat.Tema', verbose_name='cím')),
            ],
            options={
                'verbose_name': 'hallgató témája képzésen',
                'verbose_name_plural': 'hallgatók témái képzésen',
                'ordering': ['hallgato_kepzes', 'kezdet'],
                'unique_together': {('hallgato_kepzes', 'tema', 'kezdet')},
            },
        ),
        migrations.AddField(
            model_name='hallgatokepzes',
            name='kepzes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szakdolgozat.Kepzes', verbose_name='képzés'),
        ),
        migrations.AddField(
            model_name='hallgatokepzes',
            name='statusz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szakdolgozat.Statusz', verbose_name='státusz'),
        ),
        migrations.AddField(
            model_name='hallgatokepzes',
            name='temak',
            field=models.ManyToManyField(through='szakdolgozat.HallgatoKepzesTema', to='szakdolgozat.Tema', verbose_name='témák'),
        ),
        migrations.AlterUniqueTogether(
            name='hallgatokepzes',
            unique_together={('hallgato', 'kepzes', 'kezdet')},
        ),
    ]
