# Generated by Django 3.0.6 on 2020-06-07 17:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0006_auto_20200601_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temavezeto',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='telefon'),
        ),
    ]
