# Generated by Django 3.1.1 on 2020-09-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0007_auto_20200607_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temakor',
            options={'ordering': ['cim'], 'verbose_name': 'témakör', 'verbose_name_plural': 'témakörök'},
        ),
    ]
