# Generated by Django 3.1.1 on 2020-09-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0008_auto_20200908_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallgatokepzestema',
            options={'ordering': ['hallgato_kepzes', 'kezdet'], 'verbose_name': 'hallgató szakdolgozat címe képzésen', 'verbose_name_plural': 'hallgatók szakdolgozat címei képzésen'},
        ),
        migrations.AlterModelOptions(
            name='temavezetotemakor',
            options={'ordering': ['temavezeto', 'temakor'], 'verbose_name': 'témavezető témaköre', 'verbose_name_plural': 'témavezetők témakörei'},
        ),
        migrations.AlterField(
            model_name='tema',
            name='temavezeto_temakor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szakdolgozat.temavezetotemakor', verbose_name='témavezető témaköre'),
        ),
        migrations.AlterField(
            model_name='temavezetotemakor',
            name='temakor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szakdolgozat.temakor', verbose_name='témakör'),
        ),
    ]
