# Generated by Django 3.1.1 on 2020-09-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0009_auto_20200908_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='temavezeto',
            name='inaktiv',
            field=models.BooleanField(default=False, verbose_name='inaktív'),
        ),
    ]
