# Generated by Django 3.1.1 on 2020-09-27 10:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0010_temavezeto_inaktiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beallitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, unique='True', verbose_name='név')),
                ('ertek', models.CharField(max_length=200, verbose_name='érték')),
                ('szoveg', tinymce.models.HTMLField(blank=True, max_length=100000, null=True, verbose_name='szöveg')),
                ('magyarazat', models.CharField(blank=True, max_length=400, null=True, verbose_name='magyarázat')),
            ],
            options={
                'verbose_name': 'beállítás',
                'verbose_name_plural': 'beállítások',
                'ordering': ['nev'],
            },
        ),
    ]
