# Generated by Django 3.1.2 on 2020-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0012_auto_20200927_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='temavezeto',
            name='sorszam',
            field=models.IntegerField(blank=True, null=True, unique='True', verbose_name='sorszám'),
        ),
    ]
