# Generated by Django 3.1.6 on 2021-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0013_temavezeto_sorszam'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallgatokepzestema',
            name='szakdolgozat_link',
            field=models.URLField(blank=True, null=True, verbose_name='szakdolgozat link'),
        ),
    ]
