# Generated by Django 4.0.3 on 2022-03-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0014_hallgatokepzestema_szakdolgozat_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beallitas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='erdemjegy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hallgato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hallgatokepzes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hallgatokepzestema',
            name='erdemjegy',
            field=models.ForeignKey(blank=True, help_text='A témavezető és az opponens által adott jegy átlaga, az opponens által dott jegy felé kerekítve, azaz a Szakdolgozat tárgyra kapott jegy.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szakdolgozat.erdemjegy', verbose_name='érdemjegy'),
        ),
        migrations.AlterField(
            model_name='hallgatokepzestema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hallgatokepzestema',
            name='kerveny',
            field=models.CharField(choices=[('kerveny_00', 'Még nem volt kérvény'), ('kerveny_01', 'Első kérvény'), ('kerveny_02', 'Második kérvény')], default='kerveny_00', help_text='Ezt a mezőt még nem használjuk, a fentebbi jelölőnégyzetet kell használni.', max_length=12, verbose_name='hányszor kérvényezte a témavezetői segítséget'),
        ),
        migrations.AlterField(
            model_name='kepzes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tagozat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temakor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temastatusz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temavezeto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temavezetotemakor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
