# Generated by Django 4.0.3 on 2022-03-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0015_alter_beallitas_id_alter_erdemjegy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallgatokepzestema',
            name='erdemjegy',
            field=models.ForeignKey(blank=True, help_text='A témavezető és az opponens által adott jegy átlaga, az opponens által adott jegy felé kerekítve, azaz a Szakdolgozat tárgyra kapott jegy.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='szakdolgozat.erdemjegy', verbose_name='érdemjegy'),
        ),
    ]
