# Generated by Django 4.0.3 on 2022-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0016_alter_hallgatokepzestema_erdemjegy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallgatokepzestema',
            name='sikeres_vedes_datuma',
            field=models.DateField(blank=True, null=True, verbose_name='sikeres védés dátuma'),
        ),
    ]
