# Generated by Django 5.2.4 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szakdolgozat', '0017_hallgatokepzestema_sikeres_vedes_datuma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beallitas',
            name='nev',
            field=models.CharField(max_length=200, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='erdemjegy',
            name='ertek',
            field=models.IntegerField(unique=True, verbose_name='érték'),
        ),
        migrations.AlterField(
            model_name='erdemjegy',
            name='nev',
            field=models.CharField(max_length=15, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='kepzes',
            name='kepzes_kod',
            field=models.CharField(max_length=10, unique=True, verbose_name='képzés kód'),
        ),
        migrations.AlterField(
            model_name='statusz',
            name='nev',
            field=models.CharField(max_length=30, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='tagozat',
            name='nev',
            field=models.CharField(max_length=20, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='cim',
            field=models.CharField(max_length=255, unique=True, verbose_name='cím'),
        ),
        migrations.AlterField(
            model_name='temakor',
            name='cim',
            field=models.CharField(max_length=255, unique=True, verbose_name='cím'),
        ),
        migrations.AlterField(
            model_name='temastatusz',
            name='nev',
            field=models.CharField(max_length=50, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='temavezeto',
            name='sorszam',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='sorszám'),
        ),
    ]
