# Generated by Django 3.0.6 on 2020-06-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Munkarend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=20, unique='True', verbose_name='név')),
            ],
            options={
                'verbose_name': 'munkarend',
                'verbose_name_plural': 'munkarendek',
                'ordering': ['nev'],
            },
        ),
    ]
