# Generated by Django 3.0.6 on 2020-06-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kovetelmeny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=40, unique='True', verbose_name='név')),
            ],
            options={
                'verbose_name': 'követelmény',
                'verbose_name_plural': 'követelmények',
                'ordering': ['nev'],
            },
        ),
    ]
