# Generated by Django 3.0.6 on 2020-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0002_kovetelmeny'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurzustipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=30, unique='True', verbose_name='név')),
            ],
            options={
                'verbose_name': 'kurzustípus',
                'verbose_name_plural': 'kurzustípusok',
                'ordering': ['nev'],
            },
        ),
    ]
