# Generated by Django 3.0.6 on 2020-06-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0004_vizsgatipus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oktatotipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=50, unique='True', verbose_name='név')),
            ],
            options={
                'verbose_name': 'oktatótípus',
                'verbose_name_plural': 'oktatótípusok',
                'ordering': ['nev'],
            },
        ),
    ]
