# Generated by Django 3.0.6 on 2020-06-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0009_szak'),
    ]

    operations = [
        migrations.CreateModel(
            name='NagyTargyCsoport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='név')),
                ('szak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintatanterv.Szak', verbose_name='szak')),
            ],
            options={
                'verbose_name': 'nagytárgycsoport',
                'verbose_name_plural': 'nagytárgycsoportok',
                'unique_together': {('nev', 'szak')},
            },
        ),
    ]
