# Generated by Django 3.0.6 on 2020-06-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0010_nagytargycsoport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Szakirany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='név')),
                ('szak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintatanterv.Szak', verbose_name='szak')),
            ],
            options={
                'verbose_name': 'szakirány',
                'verbose_name_plural': 'szakirányok',
                'unique_together': {('nev', 'szak')},
            },
        ),
    ]
