# Generated by Django 3.0.6 on 2020-06-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0012_specializacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NagyTargy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targykod', models.CharField(max_length=10, unique='True', verbose_name='tárgykód')),
                ('targynev', models.CharField(max_length=200, verbose_name='tárgynév')),
                ('kredit', models.IntegerField(verbose_name='kredit')),
                ('nagytargycsoport', models.ManyToManyField(blank=True, related_name='nagytargycsoport', to='mintatanterv.NagyTargyCsoport', verbose_name='nagytárgycsoport')),
            ],
            options={
                'verbose_name': 'nagytárgy',
                'verbose_name_plural': 'nagytárgyak',
                'ordering': ['targykod'],
            },
        ),
        migrations.CreateModel(
            name='NagyTargyOktato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nagytargy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintatanterv.NagyTargy', verbose_name='nagytárgy')),
                ('oktato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintatanterv.Oktato', verbose_name='oktató')),
                ('oktato_tipus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintatanterv.Oktatotipus', verbose_name='oktató típus')),
            ],
            options={
                'verbose_name': 'nagytárgy oktató',
                'verbose_name_plural': 'nagytárgyak oktatói',
                'unique_together': {('nagytargy', 'oktato', 'oktato_tipus')},
            },
        ),
        migrations.AddField(
            model_name='nagytargy',
            name='oktato',
            field=models.ManyToManyField(blank=True, through='mintatanterv.NagyTargyOktato', to='mintatanterv.Oktato', verbose_name='oktató'),
        ),
        migrations.AddField(
            model_name='nagytargy',
            name='szak',
            field=models.ManyToManyField(blank=True, related_name='szak', to='mintatanterv.Szak', verbose_name='szak'),
        ),
        migrations.AddField(
            model_name='nagytargy',
            name='szakirany',
            field=models.ManyToManyField(blank=True, related_name='szakirany', to='mintatanterv.Szakirany', verbose_name='szakirány'),
        ),
    ]
