# Generated by Django 3.0.6 on 2020-06-07 16:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0015_auto_20200607_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='oktato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='oktato',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+00000000000', max_length=128, region=None, verbose_name='telefon'),
        ),
    ]
