# Generated by Django 3.1.6 on 2021-02-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0018_auto_20200607_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elofeltetel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eros_elofeltetel', models.BooleanField(default=False, verbose_name='erős előfeltétel')),
                ('elofeltetel_targy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elofelteteltargy', to='mintatanterv.targy', verbose_name='előfeltétel tárgy')),
                ('targy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotargy', to='mintatanterv.targy', verbose_name='tárgy')),
            ],
            options={
                'verbose_name': 'előfeltétel',
                'verbose_name_plural': 'előfeltételek',
                'unique_together': {('targy', 'elofeltetel_targy')},
            },
        ),
        migrations.AddField(
            model_name='targy',
            name='elofeltetel_targy_tipussal',
            field=models.ManyToManyField(blank=True, related_name='ezentargyakelofelteteletipussal', through='mintatanterv.Elofeltetel', to='mintatanterv.Targy', verbose_name='előfeltétel tárgy típussal'),
        ),
    ]
