# Generated by Django 3.1.6 on 2021-02-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0019_auto_20210215_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElofeltetelMintatantervben',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eros_elofeltetel', models.BooleanField(default=False, verbose_name='erős előfeltétel')),
                ('elofeltetel_targy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elofelteteltargymintatantervben', to='mintatanterv.targy', verbose_name='előfeltétel tárgy')),
                ('targy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotargymintatantervben', to='mintatanterv.mintatantervtargy', verbose_name='mintatantervtárgy')),
            ],
            options={
                'verbose_name': 'előfeltétel mintatantervben',
                'verbose_name_plural': 'előfeltételek mintatantervben',
                'unique_together': {('targy', 'elofeltetel_targy')},
            },
        ),
        migrations.AddField(
            model_name='mintatantervtargy',
            name='elofeltetel_targy_tipussal',
            field=models.ManyToManyField(blank=True, related_name='ezenmintatantervtargyakelofelteteletipussal', through='mintatanterv.ElofeltetelMintatantervben', to='mintatanterv.Targy', verbose_name='előfeltétel tárgy típussal'),
        ),
    ]
