# Generated by Django 5.2.4 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintatanterv', '0021_alter_elofeltetel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felveteltipusa',
            name='nev',
            field=models.CharField(max_length=50, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='kepzesiszint',
            name='nev',
            field=models.CharField(max_length=100, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='kovetelmeny',
            name='nev',
            field=models.CharField(max_length=40, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='kurzustipus',
            name='nev',
            field=models.CharField(max_length=30, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='mintatanterv',
            name='kod',
            field=models.CharField(max_length=10, unique=True, verbose_name='kód'),
        ),
        migrations.AlterField(
            model_name='munkarend',
            name='nev',
            field=models.CharField(max_length=20, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='nagytargy',
            name='targykod',
            field=models.CharField(max_length=10, unique=True, verbose_name='tárgykód'),
        ),
        migrations.AlterField(
            model_name='oktatotipus',
            name='nev',
            field=models.CharField(max_length=50, unique=True, verbose_name='név'),
        ),
        migrations.AlterField(
            model_name='targy',
            name='targykod',
            field=models.CharField(max_length=20, unique=True, verbose_name='tárgykód'),
        ),
        migrations.AlterField(
            model_name='vizsgatipus',
            name='nev',
            field=models.CharField(max_length=50, unique=True, verbose_name='név'),
        ),
    ]
