# Generated by Django 3.0.6 on 2020-05-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szabalyzat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, unique='True', verbose_name='név')),
                ('link', models.URLField(help_text='A szabályzatra mutató link.', unique='True')),
                ('csak_oktatoknak', models.BooleanField(default=False, verbose_name='csak oktatóknak')),
            ],
            options={
                'verbose_name_plural': 'szabályzatok',
                'ordering': ['nev'],
            },
        ),
    ]
