# Generated by Django 5.2.4 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szabalyzat', '0004_alter_szabalyzat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szabalyzat',
            name='nev',
            field=models.CharField(max_length=200, unique=True, verbose_name='név'),
        ),
    ]
