# Generated by Django 3.0.6 on 2020-06-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beallitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, unique='True', verbose_name='név')),
                ('ertek', models.CharField(max_length=200, verbose_name='érték')),
                ('magyarazat', models.CharField(blank=True, max_length=400, null=True, verbose_name='magyarázat')),
            ],
            options={
                'verbose_name': 'beállítás',
                'verbose_name_plural': 'beállítások',
                'ordering': ['nev'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Hallgatói link esetében "...years_days_horizontal.html", oktatói link esetében pedig "...teachers_days_horizontal.html" végű linket kell ide beírni. Ha rossz a link, akkor hibaüzenetet ír ki az oldal.', unique='True')),
                ('oktatoi_link', models.BooleanField(default=False, help_text='Ha nincs kipipálva, akkor ez egy hallgatói link.', verbose_name='oktatói link')),
                ('aktiv', models.BooleanField(default=False, verbose_name='aktív')),
            ],
            options={
                'verbose_name_plural': 'linkek',
                'ordering': ['oktatoi_link', 'link'],
            },
        ),
    ]
