# Generated by Django 3.0.7 on 2020-06-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orarend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrarendFajl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orarendfajl', models.FileField(upload_to='orarendek/')),
            ],
            options={
                'verbose_name': 'órarendfájl',
                'verbose_name_plural': 'órarendfájlok',
            },
        ),
    ]
