# Generated by Django 3.0.7 on 2020-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orarend', '0002_orarendfajl'),
    ]

    operations = [
        migrations.AddField(
            model_name='orarendfajl',
            name='aktiv',
            field=models.BooleanField(default=False, verbose_name='aktív'),
        ),
        migrations.AddField(
            model_name='orarendfajl',
            name='oktatoi_orarendfajl',
            field=models.BooleanField(default=False, help_text='Ha nincs kipipálva, akkor ez egy hallgatói órarendfájl.', verbose_name='oktatói órarendfájl'),
        ),
        migrations.AlterField(
            model_name='orarendfajl',
            name='orarendfajl',
            field=models.FileField(upload_to='orarendek/', verbose_name='órarendfájl'),
        ),
    ]
