# Generated by Django 3.0.7 on 2020-06-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orarend', '0003_auto_20200608_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AlterField(
            model_name='orarendfajl',
            name='orarendfajl',
            field=models.FileField(help_text='Hallgatói órarendfájl esetében "...years_days_horizontal.html", oktatói órarendfájl esetében pedig "...teachers_days_horizontal.html" végű órarendfájlt kell ide feltölteni. Más fájlok esetén hibaüzenetet ír ki az oldal.', upload_to='orarendek/', verbose_name='órarendfájl'),
        ),
    ]
