# Generated by Django 5.2.4 on 2026-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orarend', '0005_alter_beallitas_id_alter_orarendfajl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beallitas',
            name='nev',
            field=models.CharField(max_length=200, unique=True, verbose_name='név'),
        ),
    ]
